# Nombre de la aplicación
spring.application.name=practica-git-java-spring

# Puerto del servidor
server.port=8080

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:practicadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola web de H2 disponible en /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
